@echo off
echo Starting SRP Airconditioning Website with minimal config...
echo.
echo Backing up current config...
copy next.config.js next.config.backup.js
echo.
echo Using minimal configuration...
copy next.config.minimal.js next.config.js
echo.
echo Starting development server...
npx next dev
echo.
echo Restoring original config...
copy next.config.backup.js next.config.js
pause
